Controllers/AirfibrePackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JPSEMWebApp.Data;
using JPSEMWebApp.Models;
using JPSEMWebApp.ViewModels;

namespace JPSEMWebApp.Controllers
{
    public class AirfibrePackagesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AirfibrePackagesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AirfibrePackages
        public async Task<IActionResult> Index( int page = 1, int pageSize = 4)
        {
            var totalItems = await _context.AirfibrePackages.CountAsync();
            var totalPages = (int)Math.Ceiling((double)totalItems / pageSize);

            var airfibrePackages = await _context.AirfibrePackages
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            var model = new PaginatedAirfibrePackagesViewModel
            {
                AirfibrePackages = airfibrePackages,
                PageNumber = page,
                PageSize = pageSize,
                TotalPages = totalPages
            };

            return View(model);
              //return _context.AirfibrePackages != null ? 
              //            View(await _context.AirfibrePackages.ToListAsync()) :
              //            Problem("Entity set 'ApplicationDbContext.AirfibrePackages'  is null.");
        }

        // GET: AirfibrePackages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AirfibrePackages == null)
            {
                return NotFound();
            }

            var airfibrePackage = await _context.AirfibrePackages
                .FirstOrDefaultAsync(m => m.AirfibrePackageId == id);
            if (airfibrePackage == null)
            {
                return NotFound();
            }

            return View(airfibrePackage);
        }

        // GET: AirfibrePackages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AirfibrePackages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AirfibrePackageId,Speed,Description,Capicity,Price,InstallationPrice")] AirfibrePackage airfibrePackage)
        {
            if (ModelState.IsValid)
            {
                _context.Add(airfibrePackage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(airfibrePackage);
        }

        // GET: AirfibrePackages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AirfibrePackages == null)
            {
                return NotFound();
            }

            var airfibrePackage = await _context.AirfibrePackages.FindAsync(id);
            if (airfibrePackage == null)
            {
                return NotFound();
            }
            return View(airfibrePackage);
        }

        // POST: AirfibrePackages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AirfibrePackageId,Speed,Description,Capicity,Price,InstallationPrice")] AirfibrePackage airfibrePackage)
        {
            if (id != airfibrePackage.AirfibrePackageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(airfibrePackage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AirfibrePackageExists(airfibrePackage.AirfibrePackageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(airfibrePackage);
        }

        // GET: AirfibrePackages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AirfibrePackages == null)
            {
                return NotFound();
            }

            var airfibrePackage = await _context.AirfibrePackages
                .FirstOrDefaultAsync(m => m.AirfibrePackageId == id);
            if (airfibrePackage == null)
            {
                return NotFound();
            }

            return View(airfibrePackage);
        }

        // POST: AirfibrePackages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AirfibrePackages == null)
            {
                return Problem("Entity set 'ApplicationDbContext.AirfibrePackages'  is null.");
            }
            var airfibrePackage = await _context.AirfibrePackages.FindAsync(id);
            if (airfibrePackage != null)
            {
                _context.AirfibrePackages.Remove(airfibrePackage);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AirfibrePackageExists(int id)
        {
          return (_context.AirfibrePackages?.Any(e => e.AirfibrePackageId == id)).GetValueOrDefault();
        }
    }
}

Controllers/BusinessPackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JPSEMWebApp.Data;
using JPSEMWebApp.Models;
using JPSEMWebApp.ViewModels;

namespace JPSEMWebApp.Controllers
{
    public class BusinessPackagesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BusinessPackagesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: BusinessPackages
        public async Task<IActionResult> Index(int page = 1, int pageSize = 4)
        {
            var totalItems = await _context.BusinessPackages.CountAsync();
            var totalPages = (int)Math.Ceiling((double)totalItems / pageSize);

            var businessPackages = await _context.BusinessPackages
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            var model = new PaginatedBusinessPackagesViewModel
            {
                BusinessPackages = businessPackages,
                PageNumber = page,
                PageSize = pageSize,
                TotalPages = totalPages
            };

            return View(model);
        }


        // GET: BusinessPackages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BusinessPackages == null)
            {
                return NotFound();
            }

            var businessPackage = await _context.BusinessPackages
                .FirstOrDefaultAsync(m => m.BusinessPackageId == id);
            if (businessPackage == null)
            {
                return NotFound();
            }

            return View(businessPackage);
        }

        // GET: BusinessPackages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BusinessPackages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BusinessPackageId,Speed,Description,Capacity,Price,RedundancyPrice,InstallationPrice")] BusinessPackage businessPackage)
        {
            if (ModelState.IsValid)
            {
                _context.Add(businessPackage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(businessPackage);
        }

        // GET: BusinessPackages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BusinessPackages == null)
            {
                return NotFound();
            }

            var businessPackage = await _context.BusinessPackages.FindAsync(id);
            if (businessPackage == null)
            {
                return NotFound();
            }
            return View(businessPackage);
        }

        // POST: BusinessPackages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BusinessPackageId,Speed,Description,Capacity,Price,RedundancyPrice,InstallationPrice")] BusinessPackage businessPackage)
        {
            if (id != businessPackage.BusinessPackageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(businessPackage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BusinessPackageExists(businessPackage.BusinessPackageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(businessPackage);
        }

        // GET: BusinessPackages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BusinessPackages == null)
            {
                return NotFound();
            }

            var businessPackage = await _context.BusinessPackages
                .FirstOrDefaultAsync(m => m.BusinessPackageId == id);
            if (businessPackage == null)
            {
                return NotFound();
            }

            return View(businessPackage);
        }

        // POST: BusinessPackages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BusinessPackages == null)
            {
                return Problem("Entity set 'ApplicationDbContext.BusinessPackages'  is null.");
            }
            var businessPackage = await _context.BusinessPackages.FindAsync(id);
            if (businessPackage != null)
            {
                _context.BusinessPackages.Remove(businessPackage);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BusinessPackageExists(int id)
        {
          return (_context.BusinessPackages?.Any(e => e.BusinessPackageId == id)).GetValueOrDefault();
        }
    }
}

Controllers/LtePackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JPSEMWebApp.Data;
using JPSEMWebApp.Models;
using JPSEMWebApp.ViewModels;

namespace JPSEMWebApp.Controllers
{
    public class LtePackagesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LtePackagesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LtePackages
        public async Task<IActionResult> Index( int page = 1, int pageSize = 4)
        {
            var totalItems = await _context.LtePackages.CountAsync();
            var totalPages = (int)Math.Ceiling((double)totalItems / pageSize);

            var ltePackages = await _context.LtePackages
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            var model = new PaginatedLTEPackagesViewModel
            {
                LtePackages = ltePackages,
                PageNumber = page,
                PageSize = pageSize,
                TotalPages = totalPages
            };

            return View(model);

              //return _context.LtePackages != null ? 
              //            View(await _context.LtePackages.ToListAsync()) :
              //            Problem("Entity set 'ApplicationDbContext.LtePackages'  is null.");
        }

        // GET: LtePackages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.LtePackages == null)
            {
                return NotFound();
            }

            var ltePackage = await _context.LtePackages
                .FirstOrDefaultAsync(m => m.LtePackageId == id);
            if (ltePackage == null)
            {
                return NotFound();
            }

            return View(ltePackage);
        }

        // GET: LtePackages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LtePackages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LtePackageId,Speed,Description,Capacity,Price,InstallationPrice")] LtePackage ltePackage)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ltePackage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ltePackage);
        }

        // GET: LtePackages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.LtePackages == null)
            {
                return NotFound();
            }

            var ltePackage = await _context.LtePackages.FindAsync(id);
            if (ltePackage == null)
            {
                return NotFound();
            }
            return View(ltePackage);
        }

        // POST: LtePackages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LtePackageId,Speed,Description,Capacity,Price,InstallationPrice")] LtePackage ltePackage)
        {
            if (id != ltePackage.LtePackageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ltePackage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LtePackageExists(ltePackage.LtePackageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ltePackage);
        }

        // GET: LtePackages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.LtePackages == null)
            {
                return NotFound();
            }

            var ltePackage = await _context.LtePackages
                .FirstOrDefaultAsync(m => m.LtePackageId == id);
            if (ltePackage == null)
            {
                return NotFound();
            }

            return View(ltePackage);
        }

        // POST: LtePackages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.LtePackages == null)
            {
                return Problem("Entity set 'ApplicationDbContext.LtePackages'  is null.");
            }
            var ltePackage = await _context.LtePackages.FindAsync(id);
            if (ltePackage != null)
            {
                _context.LtePackages.Remove(ltePackage);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LtePackageExists(int id)
        {
          return (_context.LtePackages?.Any(e => e.LtePackageId == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Services.cshtml
<section class="w3l-about-breadcrumb">
    <div class="breadcrumb-bg breadcrumb-bg-services py-5">
        <div class="container py-lg-4 py-md-3">
            <h2 class="title">Our services</h2>
            <ul class="breadcrumbs-custom-path">
                <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li class="active"><span class="fa fa-arrow-right mx-2" aria-hidden="true"></span> services page</li>
            </ul>
        </div>
    </div>
</section>
<section class="w3l-content-mid py-5">
  <style>
      .w3l-content-mid {
          position: relative;
      }

      .w3l-content-mid video {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          object-fit: cover;
          z-index: -1;
      }

      .card {
          width: 100%;
          height: 500px; /* Set a fixed height for each card */
          overflow: hidden; /* Hide any content that exceeds the height */
          border-radius: 10px;
          box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.1);
          transition: all 0.3s ease-in-out;
        }
        
        .card:hover {
          transform: translateY(-10px);
box-shadow: 0 25px 50px rgba(0,0,0,0.15);
        }

        .card img {
          width: 100%;
          height: 200px;
          object-fit: cover;
          transition: transform 0.3s ease;
        }

        .card:hover img {
          transform: scale(1.2);
        }

         .w3l-content-mid .text-container {
          position: relative;
          z-index: 1;
          text-align: center;
          color: #fff;
          padding: 50px 0;
      }

      .w3l-content-mid h3.title-w3l {
          animation: bounceIn 1s;
          font-size: 3rem;
          text-align: center;
      }

     
      
  </style>


    <div class="service-section py-5" style="margin-top: -100px;">
        <div class="text-container">
            <h3 class="title-w3l" style="animation: bounce 2s infinite;">
                JPSEM Packages
            </h3>
        </div>

        <div class="container py-md-5 py-4 HomePageImageServices">
            <div class="row justify-content-center">
                <div class="col-lg-3 col-md-6 item">
                    <div class="card">
                        <div class="card-header p-0 position-relative border-0">
                            <a href="@Url.Action("Index", "HouseholdPackages")">
                                <img class="d-block img-responsive"
                                     src="~/assets/images/household.jpg"
                                     alt="card-image" style="width: 100%; height: 250px; object-fit: cover;">
                            </a>
                        </div>
                        <br>
                        <br>
                        <div class="card-body service-details" style="text-align: center;">
                            <a href="@Url.Action("Index", "HouseholdPackages")">
                                <span class="label-style" style="color: #555; font-size: 1.58rem; font-weight: 600;">
                                    Building
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 item">
                    <div class="card">
                        <div class="card-header p-0 position-relative border-0">
                            <a href="@Url.Action("Index", "BusinessPackages")">
                                <img class="d-block img-responsive"
                                     src="~/assets/images/business.jpg"
                                     alt="card-image" style="width: 100%; height: 250px; object-fit: cover;">
                            </a>
                        </div>
                        <br>
                        <br>
                        <div class="card-body service-details" style="text-align: center;">
                            <a href="@Url.Action("Index", "BusinessPackages")">
                                <span class="label-style" style="color: #555; font-size: 1.58rem; font-weight: 600;">
                                    Business Package
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 item">
                    <div class="card">
                        <div class="card-header p-0 position-relative border-0">
                            <a href="@Url.Action("Index", "LtePackages")">
                                <img class="d-block img-responsive"
                                     src="~/assets/images/lte.jpg"
                                     alt="card-image" style="width: 100%; height: 250px; object-fit: cover;">
                            </a>
                        </div>
                        <br>
                        <br>
                        <div class="card-body service-details" style="text-align: center;">
                            <a href="@Url.Action("Index", "LtePackages")">
                                <span class="label-style" style="color: #555; font-size: 1.58rem; font-weight: 600;">
                                    LTE
                                </span>
                        </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 item">
                    <div class="card">
                        <div class="card-header p-0 position-relative border-0">
                            <a href="@Url.Action("Index", "AirfibrePackages")">
                                <img class="d-block img-responsive"
                                     src="~/assets/images/airfibre.jpg"
                                     alt="card-image" style="width: 100%; height: 250px; object-fit: cover;">
                            </a>
                        </div>
                        <br>
                        <br>
                        <div class="card-body service-details" style="text-align: center;">
                            <a href="@Url.Action("Index", "AirfibrePackages")">
                                <span class="label-style" style="color: #555; font-size: 1.58rem; font-weight: 600;">
                                    AirFibre
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

 
</section>
<!-- services page pricing block -->
<section class="w3l-content py-5" id="features">
    <div class="content-4-main py-lg-5 py-md-4 py-2">
        <div class="container">
            <div class="content-info-in row">
                <div class="content-left col-lg-6">
                    <img src="~/assets/images/services.jpg" class="img-fluid radius-image" alt="">
                </div>
                <div class="content-right col-lg-6 pl-lg-4 mt-lg-0 mt-5 align-self">
                    <div class="row content4-right-grids mb-md-5 mb-5">
                        <div class="col-2 content4-right-icon">
                            <div class="content4-icon">
                                <h4><strong>01.</strong></h4>
                            </div>
                        </div>
                        <div class="col-10 content4-right-info">
                            <h6><a href="#url">Initial Planning</a></h6>
                            <p>Our team will develop detailed design and technical specifications.</p>
                        </div>
                    </div>
                    <div class="row content4-right-grids mb-md-5 mb-5">
                        <div class="col-2 content4-right-icon">
                            <div class="content4-icon">
                                <h4><strong>02.</strong></h4>
                            </div>
                        </div>
                        <div class="col-10 content4-right-info">
                            <h6><a href="#url"> Development</a></h6>
                            <p>The technical side of the telecommunications development process begins. </p>
                        </div>
                    </div>
                    <div class="row content4-right-grids mb-md-5 mb-5">
                        <div class="col-2 content4-right-icon">
                            <div class="content4-icon">
                                <h4><strong>03.</strong></h4>
                            </div>
                        </div>
                        <div class="col-10 content4-right-info">
                            <h6><a href="#url"> Testing</a></h6>
                            <p>Quality assurance will test the reliability of your site.</p>
                        </div>
                    </div>
                    <div class="row content4-right-grids">
                        <div class="col-2 content4-right-icon">
                            <div class="content4-icon">
                                <h4><strong>04.</strong></h4>
                            </div>
                        </div>
                        <div class="col-10 content4-right-info">
                            <p> </p>
                            <h6><a href="#url"> Deployment & Optimisation</a></h6>
                            <p>Deployment of fibre service to your building. Fibre in the building will be supported and maintained on a monthly basis. </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="w3l-bottom1 py-5">
    <div class="container py-md-5 py-sm-4 py-2">
        <div class="row">
            <div class="col-lg-7">
                <div class="bottom-info">
                    <div class="header-section">
                        <h3 class="title-big">Start improving your Business today!</h3>
                        <p class="mt-3 pr-lg-5">
                            Our client's satisfaction is what keeps our doors open,
                            so helping you stand out is the best way to ensure that you are 100% satisfied.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 align-self text-lg-right">
                <a href="#learn" class="btn btn-style btn-outline-dark mt-lg-0 mt-md-5 mt-4 mr-2">Learn More </a>
                <a href="@Url.Action("Contact", "Home")" class="btn btn-style btn-primary mt-lg-0 mt-md-5 mt-4">Contact us</a>
            </div>
        </div>
</section>

Views/Home/thankyou.cshtml
<!-- banner section -->
<section id="home" class="w3l-banner py-5">
    <div class="container py-lg-5 py-4">
        <div class="py-lg-5 py-4 mt-lg-4">
            <div class="banner-info-grid mt-lg-5">
                <h3 class="mb-4">Thank You For Contacting JPSEM NETWORKERS</h3>
                <p>A Response to your request shall be given within the hour please check your email</p>
                <!--  <a class="btn btn-primary btn-style mt-sm-5 mt-4 mr-sm-2 mr-1" href="#more"> Know More </a> -->
                <!-- <a class="btn transparent-btn btn-style mt-sm-5 mt-4" href="about.html"> Get Started </a> -->
                <section id="bottom" class="demo">
                    <a href="#bottom"><span></span>Scroll</a>
                </section>
            </div>
        </div>
    </div>
</section>
<!-- //banner section -->